export class Requests {
    requestId:number;
    purpose:string;
    description:string;
    estimatedCost:number;
    spentAmount:number;
    advanceAmount:number;
    plannedDate:any;
    raisedBy:number;
    raisedTo:number;
    raisedOn:any;
    comments:string;
    accptedOrRejectedOn:any;
    escalationRefReqId:number;
    escalatedOn:any;
    status:number;
    updatedOn:any;
    updatedBy:number;
    updatedByName:string;
    raisedByName:string;
    raisedToName:string;
}
